language: ruby
dist: trusty
rvm:
  - 2.6
  - 2.5
gemfile:
  - Gemfile
env:
  global:
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  bundler: true

matrix:
  include:
    - gemfile: gemfiles/Gemfile.base
      rvm: 2.4
    - gemfile: gemfiles/Gemfile.edge
  allow_failures:
    - gemfile: gemfiles/Gemfile.edge

before_install:
  - gem update --system

script: "bundle exec rake"
