language: ruby
dist: trusty
rvm:
  - 2.7
  - 2.4
  - jruby-9.2.9.0
gemfile:
  - Gemfile
env:
  global:
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom

addons:
  chrome: stable

cache:
  bundler: true

matrix:
  include:
    - gemfile: gemfiles/Gemfile.base
      rvm: 2.4
    - gemfile: gemfiles/Gemfile.edge
      rvm: 2.7
  allow_failures:
    - gemfile: gemfiles/Gemfile.edge
    - rvm: jruby-9.2.9.0

before_install:
  - gem update --system

script: "bundle exec rake"
